'use strict';
const fs = require('fs');
const path = require('path');
const config = require('./config');
const db = require('./db');
const { run } = require('./runner');
const { emitLog } = require('./logbus');

// Windows process lifecycle for `nodered` / `node` runtimes via NSSM.
// Service name = nssm.prefix + site.name  (e.g. wm-nodered1).

function serviceName(site) {
  return site.service_name || `${config.nssm.prefix}${site.name}`;
}

function logFile(site) {
  return path.join(config.paths.logs, `${site.name}.log`);
}

function cleanPath(p, fallback) {
  return '/' + String(p || fallback).replace(/^\/+|\/+$/g, '');
}

// Shared Node-RED install used by every Node-RED site. Installed on demand the
// first time a Node-RED site starts (npm i into ROOT/runtimes/node-red), so no
// manual step is needed on either Mac or Windows.
function noderedRedJs() {
  return path.join(config.paths.runtimes, 'node-red', 'node_modules', 'node-red', 'red.js');
}

// Pin to Node-RED major 4: brand-new majors (5.x) silently break older contrib
// nodes (seen in the field: mcprotocol-ind loads but never connects on 5.0.1).
// Override with settings key nodered_version if a different pin is ever needed.
const NODERED_VERSION = 'node-red@4';

async function ensureNodeRedRuntime(channel) {
  if (fs.existsSync(noderedRedJs())) return true;
  const dir = path.join(config.paths.runtimes, 'node-red');
  const pkg = require('./settings').get('nodered_version') || NODERED_VERSION;
  emitLog(channel, `[node-red] runtime not installed — installing ${pkg} now (this can take a few minutes)…`);
  fs.mkdirSync(dir, { recursive: true });
  const r = await run('npm', ['install', pkg, '--no-audit', '--no-fund', '--prefix', dir], {
    channel,
    shell: true, // npm is npm.cmd on Windows
  });
  const ok = r.code === 0 && fs.existsSync(noderedRedJs());
  emitLog(channel, ok ? '[node-red] runtime installed' : '[node-red] install FAILED — see log above');
  return ok;
}

// --- Node-RED provisioning: per-site userDir + settings.js (httpRoot for path mode) ---
function noderedUserSettingsPath(site) {
  return path.join(config.paths.services, site.name, 'settings.user.js');
}

function provisionNodeRed(site) {
  const userDir = path.join(config.paths.services, site.name);
  fs.mkdirSync(userDir, { recursive: true });
  const httpRoot =
    site.exposure_mode === 'path' ? cleanPath(site.path, site.name) : '/';

  // User overrides — created ONCE, never overwritten. Edit this to add CORS,
  // adminAuth, etc. Keys here win over the managed defaults below, and survive
  // every restart / redeploy.
  const userFile = noderedUserSettingsPath(site);
  if (!fs.existsSync(userFile)) {
    fs.writeFileSync(
      userFile,
      `// Node-RED user overrides for "${site.name}".
// WEBMANAGER NEVER overwrites this file. Uncomment / add settings as needed.
//
// Enable CORS for HTTP-In (API) nodes:
//   httpNodeCors: { origin: '*', methods: 'GET,PUT,POST,DELETE,OPTIONS' },
//
// Password-protect the editor (generate hash: npx node-red-admin hash-pw):
//   adminAuth: { type: 'credentials', users: [
//     { username: 'admin', password: '<bcrypt-hash>', permissions: '*' } ] },
module.exports = {
  // httpNodeCors: { origin: '*', methods: 'GET,PUT,POST,DELETE,OPTIONS' },
};
`,
      'utf8'
    );
  }

  // Managed settings — always regenerated so uiPort/httpRoot track the site
  // config, then merged with the user overrides (user keys win).
  const settings = `// AUTO-GENERATED by WEBMANAGER — do not edit. Put overrides in settings.user.js.
const userCfg = (() => { try { return require('./settings.user.js'); } catch (e) { return {}; } })();
module.exports = Object.assign({
    uiPort: ${site.direct_port || 1880},
    httpRoot: ${JSON.stringify(httpRoot)},
    flowFile: 'flows.json',
    functionGlobalContext: {},
}, userCfg);
`;
  fs.writeFileSync(path.join(userDir, 'settings.js'), settings, 'utf8');
  return userDir;
}

// Build the NSSM `install` argv for a site based on runtime.
function installArgs(site) {
  const svc = serviceName(site);
  if (site.runtime === 'nodered') {
    const userDir = provisionNodeRed(site);
    const redJs = path.join(config.paths.runtimes, 'node-red', 'node_modules', 'node-red', 'red.js');
    return {
      svc,
      program: config.nodeExe,
      args: [redJs, '-u', userDir, '-p', String(site.direct_port || 1880), '-s', path.join(userDir, 'settings.js')],
      appDir: userDir,
    };
  }
  // generic node app: run from its repo dir, entry from package.json main (server.js default)
  const repoDir = path.join(config.paths.sites, site.name, 'repo');
  return {
    svc,
    program: config.nodeExe,
    args: [path.join(repoDir, process.env.NODE_ENTRY || 'server.js')],
    appDir: repoDir,
    env: site.direct_port ? `PORT=${site.direct_port}` : null,
  };
}

async function nssm(args, channel) {
  return run(config.nssm.exe, args, { channel });
}

async function exists(site) {
  const r = await nssm(['status', serviceName(site)], 'silent');
  return r.code === 0;
}

async function install(site, channel) {
  const a = installArgs(site);
  if (await exists(site)) {
    emitLog(channel, `[svc] ${a.svc} already installed`);
  } else {
    const r = await nssm(['install', a.svc, a.program, ...a.args], channel);
    if (r.code !== 0) return r;
    await nssm(['set', a.svc, 'AppDirectory', a.appDir], channel);
    await nssm(['set', a.svc, 'AppStdout', logFile(site)], channel);
    await nssm(['set', a.svc, 'AppStderr', logFile(site)], channel);
    await nssm(['set', a.svc, 'AppRotateFiles', '1'], channel);
    await nssm(['set', a.svc, 'Start', 'SERVICE_AUTO_START'], channel);
    if (a.env) await nssm(['set', a.svc, 'AppEnvironmentExtra', a.env], channel);
  }
  db.prepare('UPDATE sites SET service_name=? WHERE id=?').run(a.svc, site.id);
  return { code: 0 };
}

async function start(site, channel) {
  await install(site, channel);
  const r = await nssm(['start', serviceName(site)], channel);
  await refreshStatus(site);
  return r;
}
async function stop(site, channel) {
  const r = await nssm(['stop', serviceName(site)], channel);
  await refreshStatus(site);
  return r;
}
async function restart(site, channel) {
  emitLog(channel, `[svc] restart ${serviceName(site)}`);
  await nssm(['restart', serviceName(site)], channel);
  await refreshStatus(site);
  return { code: 0 };
}
async function remove(site, channel) {
  await nssm(['stop', serviceName(site)], channel);
  return nssm(['remove', serviceName(site), 'confirm'], channel);
}

async function refreshStatus(site) {
  const r = await nssm(['status', serviceName(site)], 'silent');
  const status = (r.out || '').trim() || 'unknown';
  db.prepare('UPDATE sites SET process_status=? WHERE id=?').run(status, site.id);
  return status;
}

// Tail the last N lines of a site's NSSM log into the log channel.
function tailLog(site, channel, lines = 200) {
  const f = logFile(site);
  if (!fs.existsSync(f)) {
    emitLog(channel, `[svc] no log yet at ${f}`);
    return;
  }
  const data = fs.readFileSync(f, 'utf8').split(/\r?\n/);
  for (const l of data.slice(-lines)) if (l) emitLog(channel, l);
}

module.exports = {
  serviceName,
  logFile,
  install,
  start,
  stop,
  restart,
  remove,
  refreshStatus,
  tailLog,
  provisionNodeRed,
  noderedUserSettingsPath,
  ensureNodeRedRuntime,
};
